routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
}); */

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/authenticate/remote/{user}/{key}', 'ImpersonateUser@Impersonate');

Route::get('pages/trash', 'PagesController@trash')->name('pages.trash');
Route::get('pages/{id}/forcedelete', 'PagesController@forceDelete')->name('pages.forcedelete');
Route::get('pages/{id}/restore', 'PagesController@restore')->name('pages.restore');
Route::get('pages/{id}/clone', 'PagesController@clone')->name('pages.clone');

Route::resource('pages', 'PagesController');
Route::get('/snippets/snippet', 'PagesController@snippets')->name('pages.snippets');
Route::get('themes', 'ThemesController@index')->name('themes.index');
Route::get('themes/activate/{theme}', 'ThemesController@store')->name('themes.store');
Route::get('themes/remove/{theme}', 'ThemesController@remove')->name('themes.remove');

Route::post('pages/savehtml', 'PagesController@savehtml')->name('pages.savehtml');
Route::post('pages/saveimage', 'PagesController@saveimage')->name('pages.saveimage');
Route::post('pages/savecover', 'PagesController@savecover')->name('pages.savecover');
Route::get('pages/{id}/preview', 'PagesController@preview')->name('pages.preview');
Route::get('pages/{id}/preview-trash', 'PagesController@previewTrash')->name('pages.preview-trash');

Route::get('settings/general', 'SettingsController@general')->name('settings.general');
Route::get('settings/misc', 'PreloadSettings@setting')->name('settings.host');


Route::get('settings/header', 'SettingsController@header')->name('settings.header');
Route::resource('settings/menu', 'MenuController');
Route::get('settings/footer', 'SettingsController@footer')->name('settings.footer');
Route::get('settings/footer/builder', 'SettingsController@footerbuilder')->name('settings.footerbuilder');
Route::get('settings/styles', 'SettingsController@styles')->name('settings.styles');
Route::get('settings/colors', 'SettingsController@colors')->name('settings.colors');
Route::post('settings/header/save', 'SettingsController@saveSettings')->name('settings.saveheader');
Route::post('settings/menu/save', 'SettingsController@saveSettings')->name('settings.savemenu');
Route::post('settings/footer/save', 'SettingsController@saveSettings')->name('settings.savefooter');
Route::post('settings/styles/save', 'SettingsController@saveSettings')->name('settings.saveStyles');
Route::post('settings/colors/save', 'SettingsController@saveSettings')->name('settings.savecolors');
Route::post('settings/general/save', 'SettingsController@saveSettings')->name('settings.saveGeneral');

Route::get('settings/custom', 'SettingsController@custom')->name('settings.custom');
Route::post('settings/custom/save', 'SettingsController@saveSettings')->name('settings.savecustom');


Route::post('settings/saveHost', 'PreloadSettings@saveSettings')->name('settings.saveHost');
Route::get('/publish', 'PreloadSettings@publish')->name('publish');
Route::get('/deleterepo', 'PreloadSettings@deleteRepo')->name('deleteRepo');
Route::get('/download', 'PreloadSettings@downloadhtml')->name('download');

Route::get('settings/media', 'MediaController@index')->name('media.index');
Route::post('settings/media/upload', 'MediaController@upload')->name('media.upload');
Route::post('settings/media/modalupload', 'MediaController@modalupload')->name('media.modalupload');
Route::post('settings/media/croppedupload', 'MediaController@croppedupload')->name('media.croppedupload');


Route::get('settings/mediaselect', 'MediaController@select')->name('media.select'); // Content Builder Image popup
Route::get('settings/media/delete/{id}', 'MediaController@delete')->name('media.delete');


Route::get('/seeder', 'CreateSeeder@index');
Route::post('settings/resetdb', 'CreateSeeder@resetdb');
Route::get('settings/resetdbtest', 'CreateSeeder@resetdb');
Route::post('settings/update', 'CreateSeeder@update')->name('settings.update');
Route::get('settings/updatelocal', 'CreateSeeder@updateLocal')->name('settings.updatelocal');


Route::get('/test', 'CreateSeeder@test');
Route::get('/start', 'HomeController@start')->name('start');

Route::get('/widgets', 'WidgetsController@index')->name('widgets.index');
Route::post('/widgets/save', 'WidgetsController@save')->name('widget.save');

Route::get('/buttons', 'ButtonsController@index')->name('buttons.index');
Route::post('/buttons/save', 'ButtonsController@store')->name('buttons.save');
Route::get('/buttons/{id}/edit', 'ButtonsController@edit')->name('buttons.edit');
Route::get('/buttons/{id}/delete', 'ButtonsController@delete')->name('buttons.delete');

Route::get('widgets/{id}/clone', 'WidgetsController@clone')->name('widget.clone');
Route::get('/widgets/{id}/edit', 'WidgetsController@edit')->name('widget.edit');
Route::get('/widgets/{id}/delete', 'WidgetsController@delete')->name('widget.delete');
Route::post('/widgets/preview', 'WidgetsController@preview')->name('widget.preview');
Route::get('/widgets/slide/addlayer', 'WidgetsController@addlayer')->name('widget.addlayer');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::post('/profile', 'HomeController@profileSave')->name('profileSave');


Route::get('pages/{id}/preview/public', 'CreateSeeder@previewpage');
Route::get('posts/{id}/preview/public', 'CreateSeeder@previewpost');

Route::get('posts/trash', 'PostsController@trash')->name('posts.trash');
Route::get('posts/{id}/forcedelete', 'PostsController@forceDelete')->name('posts.forcedelete');
Route::get('posts/{id}/restore', 'PostsController@restore')->name('posts.restore');

Route::resource('posts', 'PostsController');
Route::post('posts/savehtml', 'PostsController@savehtml')->name('posts.savehtml');
Route::post('posts/saveimage', 'PostsController@saveimage')->name('posts.saveimage');
Route::post('posts/savecover', 'PostsController@savecover')->name('posts.savecover');
Route::get('posts/{id}/preview', 'PostsController@preview')->name('posts.preview');
Route::get('posts/{id}/preview-trash', 'PostsController@previewTrash')->name('posts.preview-trash');
Route::get('posts/{id}/clone', 'PostsController@clone')->name('posts.clone');

Route::get('/demos', 'LoadDemo@LoadDemo')->name('loaddemo');
Route::get('/demo/create', 'LoadDemo@CreateDemo')->name('createdemo');
Route::post('/demo/import', 'LoadDemo@importDemo')->name('importDemo');

Route::resource('categories', 'CategoriesController');
Route::get('categories', 'CategoriesController@index')->name('categories.index');
Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
Route::get('categories/{id}/forcedelete', 'CategoriesController@forceDelete')->name('categories.forcedelete');
Route::get('categories/{id}/restore', 'CategoriesController@restore')->name('categories.restore');
Route::get('categories/{id}/clone', 'CategoriesController@clone')->name('categories.clone');

Route::get('popups/trash', 'PopupController@trash')->name('popups.trash');
Route::get('popups/{id}/forcedelete', 'PopupController@forceDelete')->name('popups.forcedelete');
Route::get('popups/{id}/restore', 'PopupController@restore')->name('popups.restore');
Route::get('popups/{id}/clone', 'PopupController@clone')->name('popups.clone');
Route::post('popups/savehtml', 'PopupController@savehtml')->name('popups.savehtml');
Route::resource('popups', 'PopupController');

Route::get('/user/verify/{token}', 'Auth\VerifyUserController@verifyUser');




Route::get('sections/trash', 'SectionsController@trash')->name('sections.trash');
Route::get('sections/{id}/forcedelete', 'SectionsController@forceDelete')->name('sections.forcedelete');
Route::get('sections/{id}/restore', 'SectionsController@restore')->name('sections.restore');

Route::resource('sections', 'SectionsController');
Route::post('sections/savehtml', 'SectionsController@savehtml')->name('sections.savehtml');
Route::post('sections/builderstore', 'SectionsController@builderstore')->name('sections.builderstore');
Route::post('sections/getsectionfromhtml', 'SectionsController@getSectionFromHtml')->name('sections.getSectionFromHtml');
Route::post('sections/saveimage', 'SectionsController@saveimage')->name('sections.saveimage');
Route::post('sections/savecover', 'SectionsController@savecover')->name('sections.savecover');
Route::get('sections/{id}/preview', 'SectionsController@preview')->name('sections.preview');
Route::get('sections/{id}/preview-trash', 'SectionsController@previewTrash')->name('sections.preview-trash');
Route::get('sections/{id}/clone', 'SectionsController@clone')->name('sections.clone');

resources/views/admin/buttons.blade.php
@extends('layouts.app')

@section('extra')




@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<div class="btn-group pull-right">
					<form method="post" action="{{ URL::route("buttons.save") }}">
					{{csrf_field()}}
					<button type="submit" class="btn btn-default waves-effect waves-light btn-sm pull-right">Add New Button</button>
					<input type="hidden" name="builder_background-color" value="#cccccc">
					<input type="hidden" name="builder_background-color-from" value="#cccccc">
					<input type="hidden" name="builder_background-color-to" value="#cccccc">
					<input type="hidden" name="builder_color" value="#000000">
					<input type="hidden" name="builder_font-family" value="">
					<input type="hidden" name="builder_font-size" value="16">
					<input type="hidden" name="builder_gradientbg" value="false">
					<input type="hidden" name="builder_line-height" value="16">
					<input type="hidden" name="builder_letter-spacing" value="1">
					<input type="hidden" name="builder_word-spacing" value="0">
					<input type="hidden" name="builder_text-transform" value="">
					<input type="hidden" name="builder_font-weight" value="">
					<input type="hidden" name="builder_border-style" value="none">
					<input type="hidden" name="builder_border-color" value="#000000">
					<input type="hidden" name="builder_border-top-left-radius" value="0">
					<input type="hidden" name="builder_border-top-right-radius" value="0">
					<input type="hidden" name="builder_border-bottom-left-radius" value="0">
					<input type="hidden" name="builder_border-bottom-right-radius" value="0">
					<input type="hidden" name="builder_border-left-width" value="0">
					<input type="hidden" name="builder_border-right-width" value="0">
					<input type="hidden" name="builder_border-top-width" value="0">
					<input type="hidden" name="builder_border-bottom-width" value="0">
					<input type="hidden" name="builder_padding-left" value="20">
					<input type="hidden" name="builder_padding-right" value="20">
					<input type="hidden" name="builder_padding-top" value="10">
					<input type="hidden" name="builder_padding-bottom" value="10">
					<input type="hidden" name="builder_hover_gradientbg" value="false">
					<input type="hidden" name="builder_hover_background-color" value="#cccccc">
					<input type="hidden" name="builder_hover_background-color-from" value="#cccccc">
					<input type="hidden" name="builder_hover_background-color-to" value="#cccccc">
					<input type="hidden" name="builder_hover_color" value="#000000">
					<input type="hidden" name="builder_hover_font-family" value="">
					<input type="hidden" name="builder_hover_font-size" value="16">
					<input type="hidden" name="builder_hover_line-height" value="16">
					<input type="hidden" name="builder_hover_letter-spacing" value="1">
					<input type="hidden" name="builder_hover_word-spacing" value="0">
					<input type="hidden" name="builder_hover_text-transform" value="">
					<input type="hidden" name="builder_hover_font-weight" value="">
					<input type="hidden" name="builder_hover_border-style" value="none">
					<input type="hidden" name="builder_hover_border-color" value="#000000">
					<input type="hidden" name="builder_hover_border-top-left-radius" value="0">
					<input type="hidden" name="builder_hover_border-top-right-radius" value="0">
					<input type="hidden" name="builder_hover_border-bottom-left-radius" value="0">
					<input type="hidden" name="builder_hover_border-bottom-right-radius" value="0">
					<input type="hidden" name="builder_hover_border-left-width" value="0">
					<input type="hidden" name="builder_hover_border-right-width" value="0">
					<input type="hidden" name="builder_hover_border-top-width" value="0">
					<input type="hidden" name="builder_hover_border-bottom-width" value="0">
					<input type="hidden" name="builder_hover_padding-left" value="20">
					<input type="hidden" name="builder_hover_padding-right" value="20">
					<input type="hidden" name="builder_hover_padding-top" value="10">
					<input type="hidden" name="builder_hover_padding-bottom" value="10">
					<input type="hidden" name="button_class" value="button_{{ rand(100000,100000000000) }}">
					</form>
				</div>
				<h4 class="page-title">Buttons <span>Custom Buttons</span></h4>
			</div>
			@if (\Session::has('success'))
				<div class="col-sm-12 m-t-15">
						<div class="alert alert-success">
							{!! \Session::get('success') !!}
						</div>
				</div>
			@endif
			<div class="col-sm-12 m-t-15">

				<div class="card-box">
					<table id="datatable-buttons" class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>Title</th>
								<th>Shortcode</th>
								<th>Created on</th>
							</tr>
						</thead>
						<tbody>
							@foreach (json_decode($savedbuttons) as $button)
							<tr>
								<td>
								{{ $button->name }}
								<ul class="buttons">
									<li>
										<a href="{{ route('buttons.edit', $button->id) }}"><i class="fas fa-pencil-alt"></i></a>
									</li>
									<li><a href="{{ route('buttons.delete', $button->id) }}"> <i class="fa fa-remove"></i> </a></li>
								</ul>
								</td>
								<td>
										{{ $button->shortcode }}
								</td>
								<td width="180px">Published<br />{{ $button->created_at }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>

			</div>
    </div>
</div>

@endsection

resources/views/admin/footer.blade.php
@extends('layouts.app')

@section('extra')

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
		<div class="col-sm-12">
			<h4 class="page-title">Options <span>Footer Builder</span></h4>
		</div>

			@if (\Session::has('success'))
			<div class="col-sm-12 m-t-15">
				<div class="alert alert-success">
					{!! \Session::get('success') !!}
				</div>
			</div>
			@endif
			</div>
			<div class="row m-t-15">
        <div class="col-12">
					<div class="is-wrapper" style="overflow: hidden">
					<iframe src="{{ route('settings.footerbuilder') }}" width="100%" height="1000" frameborder="0">
					<p>Your browser does not support iframes.</p>
					</iframe>
					</div>
        </div>
			</div>
    </div>
</div>

@endsection

resources/views/admin/menu.blade.php
@extends('layouts.app')

@section('extra')
<link href="{{ asset('assets/private/plugins/nestable/jquery.nestable.css') }}" rel="stylesheet" />

<style>
.panel-title{
	text-transform:none;
}
.dd{
	max-width:400px;
}
.custom-dd .dd-list .dd-item .dd-handle {
    height: 30px;
    border-radius: 0;
    background: #36404a;
	    line-height: 26px;
}
.bootstrap-select.btn-group .dropdown-menu.inner{
	max-height:300px !important;
}
.custom-dd .well{
	margin-bottom:5px;
	    padding: 10px 15px;
}
.dd3-content{
	padding-top:0;
	padding-bottom:0;
}
.dd3-content a{
	display:block;
	    padding: 5px 0;
}
.dd3-content a.deleteitem{
	    position: absolute;
    right: 6px;
    top: 0;
}
.additems .panel-default > .panel-heading{
	padding:0;
}
.additems .panel-default > .panel-heading a{
padding: 10px 20px;
display:block;
}
</style>
<script src="{{ asset('assets/private/plugins/nestable/jquery.nestable.js') }}"></script>
<script>
jQuery(document).ready(function($){
	$('#nestable_list').nestable();
})
</script>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
			<div class="col-sm-12">
				<h4 class="page-title">Options <span>Menu Settings</h4>
			</div>
			<div class="col-sm-12 m-t-15">
				<div class="card-box">
					<div class="row">
						<div class="col-sm-3">
							<p class="m-t-5 m-b-0">Select a menu to edit: </p>
						</div>
						<div class="col-sm-4">
							<div class="form-group" style="margin:0;">
							<select class="selectpicker selectmenu" data-live-search="true"  data-style="btn-white">
								<option value="">Select Menu</option>
								@foreach($menus as $menu)
								<option value="{{ $menu->id }}" @if(!empty($currentmenu) && $currentmenu->id == $menu->id) {{ "selected" }} @endif>{{ $menu->name }}</option>
								@endforeach
							</select>
							</div>
						</div>
						<div class="col-sm-5">
							<p class="m-t-5 m-b-0" style="display: inline-block"> Or <a href="{{ route('menu.create') }}">create a new menu</a>.</p>
							@if(!empty($currentmenu))
									<a href="javascript:void(0);" onclick="$(this).find('form').submit();"  class="btn btn-primary pull-right"> Delete Menu
										<form action="{{ route('menu.destroy', $currentmenu) }}" method="POST">
										{{ csrf_field() }}
										<input type="hidden" name="_method" value="DELETE">
										</form>
									</a>
							@endif
						</div>
					</div>
				</div>
			</div>
			@if (\Session::has('success'))
				<div class="col-sm-12 m-t-15">
				<div class="alert alert-success">
					{!! \Session::get('success') !!}
				</div>
				</div>
			@endif
			<div class="col-sm-12 m-t-15">

				<div class="row">
					<div class="col-sm-3 additems">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion-test-2" href="#pages" class="" aria-expanded="false">
										Pages
									</a>
								</h4>
							</div>
							<div id="pages" class="panel-collapse collapse show">
								<div class="panel-body">
									@foreach($pages as $page)
									<div class="checkbox">
										<input id="page_{{ $page->title }}" type="checkbox">
										<label for="page_{{ $page->title }}">
										{{ $page->title }}
										</label>
										<input type="hidden" name="title[]" value="{{ $page->title }}">
										<div class="checkbox_data">
											<input type="hidden" name="link[]" value="{{ $page->slug }}">
											<input type="hidden" name="type[]" value="page">
										</div>
									</div>
									@endforeach
								</div>
								<div class="panel-footer">
									<button type="button" class="btn btn-white waves-effect addpages">Add To Menu</button>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion-test-2" href="#custom" class="" aria-expanded="false">
										Custom
									</a>
								</h4>
							</div>
							<div id="custom" class="panel-collapse collapse">
								<div class="panel-body">
									<div class="form-group inlinelabel">
										<label for="title">Title:</label>
										<input type="text" class="form-control" id="title">
									</div>
									<div class="form-group inlinelabel">
										<label for="link">Link:</label>
										<input type="text" class="form-control" id="link">
									</div>
								</div>
								<div class="panel-footer">
									<button type="button" class="btn btn-white waves-effect addcustom">Add To Menu</button>
								</div>
							</div>
						</div>
					</div>

					<div class="col-sm-9">
						<form method="post" action="
						@if(!empty($currentmenu))
							{{ route("menu.update", $currentmenu->id) }}
						@else
							{{ route("menu.store") }}
						@endif
						">
						{{csrf_field()}}
						@if(!empty($currentmenu))
							<input type='hidden' name='_method' value='PATCH' />
						@endif
						<div class="panel panel-default">
							<div class="panel-heading" style="padding:5px;">
								<h4 class="panel-title">
									<div class="row">
										<div class="col-md-2">
											<p class="m-t-5 m-b-0 ml-3">Menu Name</p>
										</div>
										<div class="col-md-3 mr-auto">
											<input class="form-control" type="text" placeholder="Menu Name Here" name="menu_name" value="@if(!empty($currentmenu)) {{ $currentmenu->name }} @endif" required>
										</div>
										@if(!empty($currentmenu))
											<div class="col-md-1">
												<p class="m-t-5 m-b-0">Shortcode</p>
											</div>
											<div class="col-md-3">
												<input type="text" class="form-control" value='[menu id="{{ $currentmenu->id }}"]' readonly>
											</div>
										@endif
										<div class="col-md-3 text-right">
											@if(!empty($currentmenu))
												<button type="submit" class="btn btn-primary">Update Menu</button>
											@else
												<button type="submit" class="btn btn-primary">Create Menu</button>
											@endif
										</div>
									</div>
								</h4>
							</div>
							<div class="panel-collapse collapse show">
								<div class="panel-body">
									<div class="custom-dd dd" id="nestable_list">
										<ol class="dd-list">
										@if(!empty($currentmenu))
											{!! loopmenu($currentmenu) !!}
										@endif
										</ol>
									</div>
									<input type="hidden" name="order" value="">
								</div>
								<div class="panel-footer text-right">

									@if(!empty($currentmenu))
										<button type="submit" class="btn btn-primary">Update Menu</button>
									@else
										<button type="submit" class="btn btn-primary">Create Menu</button>
									@endif
								</div>
							</div>
						</div>
						</form>
					</div>

				</div>

			</div>

    </div>
</div>
@include('admin._partials.icons')
<script>
jQuery(document).ready(function(){
	jQuery('input[name="order"]').val(JSON.stringify(jQuery('.custom-dd').nestable('serialize')));
	jQuery('.addpages').click(function(){
		jQuery('#pages .checkbox input[type="checkbox"]').each(function(){
			var totalitem = jQuery('.dd-list li').length;
			var nextitem = Math.floor((Math.random() * 100000000) + 1);
			var inputs = '<input type="hidden" name="dataID[]" value="'+nextitem+'"><input type="hidden" name="target[]" value="_self">'+jQuery(this).parents('.checkbox').find('.checkbox_data').html();
			if(jQuery(this).is(":checked")){
				var title = jQuery(this).parents('.checkbox').find('input[name="title[]"]').val();
				var html = '<li class="dd-item" data-id="'+nextitem+'"><div class="dd-handle dd3-handle"></div><div class="dd3-content"><a href="javascript:void(0)" data-toggle="collapse" data-target="#drop'+nextitem+'">'+title+'</a><a href="javascript:void(0)" data-target="'+nextitem+'" class="deleteitem pull-right"><i class="fa fa-times" aria-hidden="true"></i></a></div>';
				html = html+inputs;
				html = html+'<div id="drop'+nextitem+'" class="collapse"><div class="well"><div class="form-group"><label class="control-label">Title</label><input class="form-control" type="text" name="title[]" value="'+title+'"></div><div class="form-group"><input class="form-control" type="hidden" name="icon[]" value=""><a href="#"  data-toggle="modal" data-target="#icon-select" class="icon-select btn btn-purple waves-effect waves-light btn-xs">Set Icon</a><i class="" style="padding:0 10px;vertical-align: middle;"></i></div><div class="form-group"><div class="form-group"><label class="control-label">Classes</label><input class="form-control" type="text" name="classes[]" value=""></div><div class="form-group"><label class="control-label">Description</label><textarea class="form-control" name="description[]"></textarea></div>';
				html = html+'<div class="checkbox"><input id="newtab'+nextitem+'" type="checkbox" class="target"><label for="newtab'+nextitem+'">Open New Tab</label></div></div></div>';
				html =html+'</li>';
				jQuery('#nestable_list .dd-list').eq(0).append(html);
				jQuery(this).prop("checked", false);
			}
		})
		jQuery('input[name="order"]').val(JSON.stringify(jQuery('.custom-dd').nestable('serialize')));
	})
	jQuery('.panel').on('click','.target',function(){
		if ($(this).is(':checked')) {
			$(this).parents('li').find('input[name="target[]"]').val('_blank');
		}else{
			$(this).parents('li').find('input[name="target[]"]').val('_self');
		}
	})
	jQuery('.addcustom').click(function(){
		var totalitem = jQuery('.dd-list li').length;
		var nextitem = Math.floor((Math.random() * 100000000) + 1);
		var title = jQuery('#custom #title').val();
		var link = jQuery('#custom #link').val();
		var inputs = '<input type="hidden" name="dataID[]" value="'+nextitem+'"><input type="hidden" name="type[]" value="custom"><input type="hidden" name="target[]" value="_self">';
		var html = '<li class="dd-item" data-id="'+nextitem+'"><div class="dd-handle dd3-handle"></div><div class="dd3-content"><a href="javascript:void(0)" data-toggle="collapse" data-target="#drop'+nextitem+'">'+title+'</a><a href="javascript:void(0)" data-target="'+nextitem+'" class="deleteitem pull-right"><i class="fa fa-times" aria-hidden="true"></i></a></div>';
		html = html+inputs;
		html = html+'<div id="drop'+nextitem+'" class="collapse"><div class="well"><div class="form-group"><label class="control-label">Title</label><input class="form-control" type="text" name="title[]" value="'+title+'"></div><div class="form-group"><input class="form-control" type="hidden" name="icon[]" value=""><a href="#"  data-toggle="modal" data-target="#icon-select" class="icon-select btn btn-purple waves-effect waves-light btn-xs">Set Icon</a><i class="" style="padding:0 10px;vertical-align: middle;"></i></div><div class="form-group"><label class="control-label">Link</label><input class="form-control" type="text" name="link[]" value="'+link+'"></div><div class="form-group"><label class="control-label">Classes</label><input class="form-control" type="text" name="classes[]" value=""></div><div class="form-group"><label class="control-label">Description</label><textarea class="form-control" name="description[]"></textarea></div>';
		html = html+'<div class="checkbox"><input id="newtab'+nextitem+'" type="checkbox" class="target"><label for="newtab'+nextitem+'">Open New Tab</label></div></div></div>';
		html =html+'</li>';

		jQuery('#nestable_list .dd-list').eq(0).append(html);

		jQuery('input[name="order"]').val(JSON.stringify(jQuery('.custom-dd').nestable('serialize')));
		jQuery('#custom #title').val('');
		jQuery('#custom #link').val('');
	})
	jQuery('.custom-dd').on('change', function() {
		jQuery('input[name="order"]').val(JSON.stringify(jQuery('.custom-dd').nestable('serialize')));
	});
	jQuery('.selectmenu').change(function(){
		window.location.href= '{{ route("menu.index") }}/'+jQuery(this).val()+'/edit';
	})
	jQuery('.custom-dd').on('click', '.deleteitem', function(){
		var item = jQuery(this);
		if (confirm('Are you sure ?')) {
			item.parents('.custom-dd').find('li[data-id="'+item.attr('data-target')+'"]').fadeOut();
			setTimeout(function(){ item.parents('.custom-dd').find('li[data-id="'+item.attr('data-target')+'"]').remove(); }, 500);
		}
	})
	jQuery('.icon-select').on('click', function(){
		jQuery('.icon-select').removeClass('selected');
		jQuery(this).addClass('selected');
	})
	jQuery('#icon-select .icon a').on('click', function(){
		var iconclass = jQuery(this).attr('data-icon');
		jQuery('.icon-select.selected').prev('input').val(iconclass);
		jQuery('.icon-select.selected').next('i').attr('class', iconclass);
		jQuery('#icon-select').modal('hide');
		return false;
	})
})
</script>
@endsection