routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
}); */

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/authenticate/remote/{user}/{key}', 'ImpersonateUser@Impersonate');

Route::get('pages/trash', 'PagesController@trash')->name('pages.trash');
Route::get('pages/{id}/forcedelete', 'PagesController@forceDelete')->name('pages.forcedelete');
Route::get('pages/{id}/restore', 'PagesController@restore')->name('pages.restore');
Route::get('pages/{id}/clone', 'PagesController@clone')->name('pages.clone');

Route::resource('pages', 'PagesController');
Route::get('/snippets/snippet', 'PagesController@snippets')->name('pages.snippets');
Route::get('themes', 'ThemesController@index')->name('themes.index');
Route::get('themes/activate/{theme}', 'ThemesController@store')->name('themes.store');
Route::get('themes/remove/{theme}', 'ThemesController@remove')->name('themes.remove');

Route::post('pages/savehtml', 'PagesController@savehtml')->name('pages.savehtml');
Route::post('pages/saveimage', 'PagesController@saveimage')->name('pages.saveimage');
Route::post('pages/savecover', 'PagesController@savecover')->name('pages.savecover');
Route::get('pages/{id}/preview', 'PagesController@preview')->name('pages.preview');
Route::get('pages/{id}/preview-trash', 'PagesController@previewTrash')->name('pages.preview-trash');

Route::get('settings/general', 'SettingsController@general')->name('settings.general');
Route::get('settings/misc', 'PreloadSettings@setting')->name('settings.host');


Route::get('settings/header', 'SettingsController@header')->name('settings.header');
Route::resource('settings/menu', 'MenuController');
Route::get('settings/footer', 'SettingsController@footer')->name('settings.footer');
Route::get('settings/footer/builder', 'SettingsController@footerbuilder')->name('settings.footerbuilder');
Route::get('settings/styles', 'SettingsController@styles')->name('settings.styles');
Route::get('settings/colors', 'SettingsController@colors')->name('settings.colors');
Route::post('settings/header/save', 'SettingsController@saveSettings')->name('settings.saveheader');
Route::post('settings/menu/save', 'SettingsController@saveSettings')->name('settings.savemenu');
Route::post('settings/footer/save', 'SettingsController@saveSettings')->name('settings.savefooter');
Route::post('settings/styles/save', 'SettingsController@saveSettings')->name('settings.saveStyles');
Route::post('settings/colors/save', 'SettingsController@saveSettings')->name('settings.savecolors');
Route::post('settings/general/save', 'SettingsController@saveSettings')->name('settings.saveGeneral');

Route::get('settings/custom', 'SettingsController@custom')->name('settings.custom');
Route::post('settings/custom/save', 'SettingsController@saveSettings')->name('settings.savecustom');


Route::post('settings/saveHost', 'PreloadSettings@saveSettings')->name('settings.saveHost');
Route::get('/publish', 'PreloadSettings@publish')->name('publish');
Route::get('/deleterepo', 'PreloadSettings@deleteRepo')->name('deleteRepo');
Route::get('/download', 'PreloadSettings@downloadhtml')->name('download');

Route::get('settings/media', 'MediaController@index')->name('media.index');
Route::post('settings/media/upload', 'MediaController@upload')->name('media.upload');
Route::post('settings/media/modalupload', 'MediaController@modalupload')->name('media.modalupload');
Route::post('settings/media/croppedupload', 'MediaController@croppedupload')->name('media.croppedupload');


Route::get('settings/mediaselect', 'MediaController@select')->name('media.select'); // Content Builder Image popup
Route::get('settings/media/delete/{id}', 'MediaController@delete')->name('media.delete');


Route::get('/seeder', 'CreateSeeder@index');
Route::post('settings/resetdb', 'CreateSeeder@resetdb');
Route::get('settings/resetdbtest', 'CreateSeeder@resetdb');
Route::post('settings/update', 'CreateSeeder@update')->name('settings.update');
Route::get('settings/updatelocal', 'CreateSeeder@updateLocal')->name('settings.updatelocal');


Route::get('/test', 'CreateSeeder@test');
Route::get('/start', 'HomeController@start')->name('start');

Route::get('/widgets', 'WidgetsController@index')->name('widgets.index');
Route::post('/widgets/save', 'WidgetsController@save')->name('widget.save');

Route::get('/buttons', 'ButtonsController@index')->name('buttons.index');
Route::post('/buttons/save', 'ButtonsController@store')->name('buttons.save');
Route::get('/buttons/{id}/edit', 'ButtonsController@edit')->name('buttons.edit');
Route::get('/buttons/{id}/delete', 'ButtonsController@delete')->name('buttons.delete');

Route::get('widgets/{id}/clone', 'WidgetsController@clone')->name('widget.clone');
Route::get('/widgets/{id}/edit', 'WidgetsController@edit')->name('widget.edit');
Route::get('/widgets/{id}/delete', 'WidgetsController@delete')->name('widget.delete');
Route::post('/widgets/preview', 'WidgetsController@preview')->name('widget.preview');
Route::get('/widgets/slide/addlayer', 'WidgetsController@addlayer')->name('widget.addlayer');
Route::get('/profile', 'HomeController@profile')->name('profile');
Route::post('/profile', 'HomeController@profileSave')->name('profileSave');


Route::get('pages/{id}/preview/public', 'CreateSeeder@previewpage');
Route::get('posts/{id}/preview/public', 'CreateSeeder@previewpost');

Route::get('posts/trash', 'PostsController@trash')->name('posts.trash');
Route::get('posts/{id}/forcedelete', 'PostsController@forceDelete')->name('posts.forcedelete');
Route::get('posts/{id}/restore', 'PostsController@restore')->name('posts.restore');

Route::resource('posts', 'PostsController');
Route::post('posts/savehtml', 'PostsController@savehtml')->name('posts.savehtml');
Route::post('posts/saveimage', 'PostsController@saveimage')->name('posts.saveimage');
Route::post('posts/savecover', 'PostsController@savecover')->name('posts.savecover');
Route::get('posts/{id}/preview', 'PostsController@preview')->name('posts.preview');
Route::get('posts/{id}/preview-trash', 'PostsController@previewTrash')->name('posts.preview-trash');
Route::get('posts/{id}/clone', 'PostsController@clone')->name('posts.clone');

Route::get('/demos', 'LoadDemo@LoadDemo')->name('loaddemo');
Route::get('/demo/create', 'LoadDemo@CreateDemo')->name('createdemo');
Route::post('/demo/import', 'LoadDemo@importDemo')->name('importDemo');

Route::resource('categories', 'CategoriesController');
Route::get('categories', 'CategoriesController@index')->name('categories.index');
Route::get('categories/trash', 'CategoriesController@trash')->name('categories.trash');
Route::get('categories/{id}/forcedelete', 'CategoriesController@forceDelete')->name('categories.forcedelete');
Route::get('categories/{id}/restore', 'CategoriesController@restore')->name('categories.restore');
Route::get('categories/{id}/clone', 'CategoriesController@clone')->name('categories.clone');

Route::get('popups/trash', 'PopupController@trash')->name('popups.trash');
Route::get('popups/{id}/forcedelete', 'PopupController@forceDelete')->name('popups.forcedelete');
Route::get('popups/{id}/restore', 'PopupController@restore')->name('popups.restore');
Route::get('popups/{id}/clone', 'PopupController@clone')->name('popups.clone');
Route::post('popups/savehtml', 'PopupController@savehtml')->name('popups.savehtml');
Route::resource('popups', 'PopupController');

Route::get('/user/verify/{token}', 'Auth\VerifyUserController@verifyUser');




Route::get('sections/trash', 'SectionsController@trash')->name('sections.trash');
Route::get('sections/{id}/forcedelete', 'SectionsController@forceDelete')->name('sections.forcedelete');
Route::get('sections/{id}/restore', 'SectionsController@restore')->name('sections.restore');

Route::resource('sections', 'SectionsController');
Route::post('sections/savehtml', 'SectionsController@savehtml')->name('sections.savehtml');
Route::post('sections/builderstore', 'SectionsController@builderstore')->name('sections.builderstore');
Route::post('sections/getsectionfromhtml', 'SectionsController@getSectionFromHtml')->name('sections.getSectionFromHtml');
Route::post('sections/saveimage', 'SectionsController@saveimage')->name('sections.saveimage');
Route::post('sections/savecover', 'SectionsController@savecover')->name('sections.savecover');
Route::get('sections/{id}/preview', 'SectionsController@preview')->name('sections.preview');
Route::get('sections/{id}/preview-trash', 'SectionsController@previewTrash')->name('sections.preview-trash');
Route::get('sections/{id}/clone', 'SectionsController@clone')->name('sections.clone');

resources/views/admin/_partials/coverimage.blade.php
<script src="{{ asset('assets/private/js/dropzone.js') }}" type="text/javascript"></script>
<div class="md-custom-modal md-custom-effect-1 media-select" id="cover-select">
	<div class="md-custom-content">
		<h3>Media</h3>
		<ul class="nav nav-tabs navtab-bg nav-justified">
			<li><a data-toggle="tab" href="#upload2">Upload Files</a></li>
			<li><a data-toggle="tab" id="medialibrary2" href="#media2" class="active">Media Library</a></li>
		</ul>
		<div class="md-custom-body">
			<div class="tab-content">
				<div id="upload2" class="tab-pane fade">
					<div class="card-box">
						<div class="hidden">
							<div id="preview-template">
								<div class="dz-preview imageholder dz-file-preview">
									<div class="dz-details">
									<div class="thumbnail active"><img data-dz-thumbnail /></div>
									</div>
									<div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
									<div class="dz-error-message"><span data-dz-errormessage></span></div>
								</div>
							</div>
						</div>
						<form action="" class="dropzone dropzone2">

						</form>
					</div>
				</div>
				<div id="media2" class="tab-pane fade in active show">
					<div class="allmedia">
					@foreach($uploads as $upload)
						<div class="imageholder">
							<div class="thumbnail"><a href="{{ getImage($upload->slug,'') }}"><img src="{{ getImage($upload->slug,'thumbnail') }}"></a></div>
						</div>
					@endforeach
					</div>
					<div class="row hidden" style="clear:both">
						<div class="col-sm-12 m-t-15">{{ $uploads->links() }}</div>
					</div>
				</div>
			</div>
		</div>
		<div class="md-custom-footer">
		<button class="md-custom-close">Close me!</button>
		</div>
	</div>
</div>
 <div  data-target="#cover-select" class="md-overlay md-custom-overlay"></div>

<script>

Dropzone.autoDiscover = false;
$(function(){
    uploader = new Dropzone(".dropzone2",{
        url: "{{ route('media.modalupload')}}",
        uploadMultiple :false,
        acceptedFiles : "image/*,video/*,audio/*",
        addRemoveLinks: false,
        forceFallback: false,
		thumbnailWidth: 190,
		thumbnailHeight: 190,
		init: function () {
			this.on('addedfile', function (file) {
			   $('#medialibrary2').trigger('click');
			   $('#media2 .allmedia').prepend($(file.previewElement));
			   $('.dropzone2').removeClass('dz-started');
			}),
			this.on("success", function(file, responseText) {
				$('#media2 .dz-success').addClass('recent');
				$('#media2 .dz-success .active').html(responseText);
				$('#media2 .dz-success .thumbnail').removeClass('active');
			}),
			this.on("error", function(file, responseText) {
				alert(responseText.errors.file);
				$('.dz-error').remove();
			})
		},
		previewTemplate: document.getElementById('preview-template').innerHTML,
        maxFilesize:1024,
        parallelUploads: 1,
		headers: {
			'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
		}
    });
});
@if(sizeof($uploads)==15)
$(document).ready(function(){
	$('#media2 .allmedia').scroll(function(){
		$('#media2 .allmedia').infiniteScroll({
			  path: '#media2 .pagination li a[rel="next"]',
			  append: '#media2 .allmedia .imageholder',
			  history: false,
			  prefill: true
			});
	})
})

@endif
$(window).bind("load", function() {
		$('#media2 .allmedia').css('height', ($('#cover-select').height()-183)+'px');
})
$(window).resize(function () {
		$('#media2 .allmedia').css('height', ($('#cover-select').height()-183)+'px');
})
</script>

resources/views/admin/_partials/footer-builder.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
<script src="{{ asset('assets/public/js/jquery.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link href="{{ asset('assets/public/css/ionicons.min.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('assets/public/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
	@if(!empty(getSetting('imported_font_link','styles')))
		@foreach(getSetting('imported_font_link','styles') as $links)
			<link href="{!! $links !!}" rel="stylesheet">
		@endforeach
	@endif
	<link href="{{ asset('assets/public/css/box.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('assets/public/css/widgets.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('assets/public/css/tipuesearch.css') }}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{ asset('assets/private/css/modal.css') }}" />
	<link href="{{ asset('builder/contentbuilder/contentbuilder.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('builder/contentbox/contentbox.css') }}" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link href="{{ asset('assets/private/css/dropzone.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('html/assets/theme-demo.css') }}" rel="stylesheet">

	<link href="{{ IncludeAsset('public/css/style.css') }}" rel="stylesheet">
	<link href="{{ asset('assets/private/css/builder.css') }}" rel="stylesheet">

<meta name="csrf-token" content="{{ csrf_token() }}">
<script>var csrf_field = '{{csrf_field()}}';</script>
<style>
  #lnkToolOpen{
	  display:none;
  }
	.sticky-wrapper {
    padding-left: 15px;
    padding-right: 15px;
}
.builder_controls ul>li>.dropdown-menu a {
    padding: 8px 15px;
    font-family: "Open Sans", sans-serif !important;
}

.builder_controls .nav>li a{
	background-color: transparent !important;
	padding:0;
	font-size: 15px !important;
	display: block;
	color: #333 !important;
			line-height: 1.5;
}
</style>
</head>
<body>
<div class="container-fluid" style="padding:0;">
    <div class="row no-gutters">
			<div id="builder_controls" class="builder_controls text-center">
				<div class="container-fluid">
					<ul class="nav justify-content-start">
						<li class="dropdown">
							<a href="javascript:void(0);" class="btn btn-primary" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-caret-left"></i></a>
							<ul class="dropdown-menu">
								<li><a href="{{ config('app.url', 'Laravel') }}">Dashboard</a></li>
								<li><a href="{{ route('settings.header') }}">Header</a></li>
								<li><a href="{{ route('menu.index') }}">Menu</a></li>
								<li><a href="{{ route('settings.styles') }}">Styles</a></li>
								<li><a href="{{ route('settings.footer') }}">Footer</a></li>
								<li><a href="{{ route('settings.custom') }}">Custom</a></li>
								<li><a href="{{URL::route('media.index')}}">Media</a></li>
								<li><a href="{{URL::route('pages.index')}}">Pages</a></li>
								<li><a href="{{URL::route('posts.index')}}">Posts</a></li>
			          <li><a href="{{URL::route('sections.index')}}">Sections</a></li>
								<li><a href="{{URL::route('widgets.index')}}">Widgets</a></li>
							</ul>
						</li>
						<li><a href="#" class="btn btn-primary" id="view-html"><i class="cb-icon-code"></i></a></li>

						<li><a href="#" class="btn btn-primary" id="add-section"><i class="cb-icon-plus"></i></a></li>

						<li style="float:right;"><a href="#" class="btn btn-primary" id="save-html" style="background-color: #f05050 !important;border: 1px solid #f05050 !important;"><i class="fa fa-save" aria-hidden="true"></i></a></li>
					</ul>
				</div>
			</div>
	</div>
</div>
			@if (\Session::has('success'))
				<div class="alert alert-success">
					{!! \Session::get('success') !!}
				</div>
				<script>
				$(document).ready(function(){
					setTimeout(function(){ $('.alert-success').fadeOut(); }, 2000);
				})
				</script>
			@endif
					<div id="is-wrapper" class="is-wrapper">
					@if(!empty($savedsettings['html']))
							{!! $savedsettings['html'] !!}
					@else
						<div class="is-section is-box is-section-auto is-dark-text is-bg-light">
								<div class="is-overlay">
									<div class="is-overlay-bg" style="display: none;"></div>
									<div class="is-overlay-color" style="display: none;"></div>
									<div class="is-overlay-content"></div>
								</div>
								<div class="is-boxes">
									<div class="is-box-centered is-opacity-80">
										<div class="is-container is-footer is-builder container-fluid" id="contentareapZ9SySj" style=""><div class="widget-cat-basic"><div class="row clearfix">
											<div class="col-md-3">
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
											</div>
											<div class="col-md-3">
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
											</div>
											<div class="col-md-3">
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
											</div>
											<div class="col-md-3">
												<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
											</div>
										</div></div></div>
									</div>
								</div>
							</div>
							@endif
			</div>
<div class="container-fluid">
	<div class="row m-t-15">
	<form id="savefooter" method="post" action="{{ route("settings.savefooter") }}" enctype="multipart/form-data">
	{{csrf_field()}}
	<input type="hidden" name="settingType" value="footer">
	<input type="hidden" id="html" name="html" value="">
	</form>
	<div class="imageselect">
	@include('admin._partials.popupuploader')
	</div>
	<div class="coverselect">
		@include('admin._partials.coverimage')
	</div>
	</div>
</div>
<script src="{{ asset('assets/private/js/classie.js') }}"></script>
<script src="{{ asset('assets/private/js/modalEffects.js') }}"></script>
<script>
  var polyfilter_scriptpath = '{{ asset("assets/private/js") }}/';
</script>
<script src="{{ asset('assets/private/js/cssParser.js') }}"></script>
<script src="{{ asset('builder/contentbuilder/jquery-ui.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('builder/contentbuilder/contentbuilder.js') }}" type="text/javascript"></script>
<script src="{{ asset('builder/contentbuilder/saveimages.js') }}" type="text/javascript"></script>
<script src="{{ asset('builder/contentbox/builderbox.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/private/plugins/simplelightbox/simple-lightbox.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/public/js/box.js') }}" type="text/javascript"></script>
<script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>
<script>
jQuery(document).ready(function($){
	$("#is-wrapper").contentbox({
		zoom: 0.85,
		snippetFile: '{{ route("pages.snippets") }}',
		contentHtmlStart: '<div class="is-container is-footer is-builder container-fluid"><div class="row"><div class="col-md-12">',
		contentHtmlEnd: '</div></div></div>',
		coverImageHandler: '{{ route("pages.savecover") }}',
		//largerImageHandler: 'saveimage-large.php', /* for uploading larger image */
		onRender: function () {
			$('a.is-lightbox').simpleLightbox({ closeText: '<i style="font-size:35px" class="icon ion-ios-close-empty"></i>', navText: ['<i class="icon ion-ios-arrow-left"></i>', '<i class="icon ion-ios-arrow-right"></i>'], disableScroll: false });
			$('.row').each(function(){
				if($(this).find('div').length>0){
					if($(this).attr('contenteditable')){
						$(this).removeAttr('contenteditable');
						$(this).find('div').attr('contenteditable', 'true');
					}
				}
			})
		},
		onImageBrowseClick: function(){
			$('#media-select').addClass('md-custom-show');
			$('#active-input').attr('value','txtImgUrl');

		},
		//imageselect: '{{ route("media.select") }}',
		iconselect: '{{ asset('builder/contentbox/ionicons/selecticon-dark.html') }}',
		snippetCustomCode: true,
		toolbar: 'top',
		snippetCategories: [
				[-1, "All"],
                [120, "Basic"],
				{!! getCustomSnippetCategories() !!}
                [118, "Article"],
                [101, "Headline"],
                [119, "Buttons"],
                [102, "Photos"],
                [103, "Profile"],
                [116, "Contact"],
                [104, "Products"],
                [105, "Features"],
                [106, "Process"],
                [107, "Pricing"],
                [108, "Skills"],
                [109, "Achievements"],
                [110, "Quotes"],
                [111, "Partners"],
                [112, "As Featured On"],
                [113, "Page Not Found"],
                [114, "Coming Soon"],
                [115, "Help, FAQ"],
                ]
	});
	$("#add-section").click(function () {
            $('#is-wrapper').data('contentbox').addSection(); //To add new section, call addSection().
            return false;
    });
	$("#view-html").click(function () {
		$('#is-wrapper').data('contentbox').viewHtml();
		return false;
	});
	$("#save-html").click(function () {
		$('img.ui-resizable').resizable( "destroy" );
		$(this).prop('disabled', true);
		$("#is-wrapper").saveimages({
			handler: '{{ route("pages.saveimage") }}', // or saveimage.php - for saving embedded base64 image to image file
			onComplete: function () {
				//Save Content
				var sHTML = $('#is-wrapper').data('contentbox').html();
				$('#html').val(sHTML);
				$('#savefooter').submit();
			}
		});
		$("#is-wrapper").data('saveimages').save();
		return false;
	});
	$('.imageselect').on('click','.imageholder a',function(){
		$('#lnkImageSettings').trigger('click');
		$('body #chkCrop').prop('checked', true);
		$('#'+$('#active-input').val()).val($(this).attr('href'));
		$('#media-select').removeClass('md-custom-show');
		return false;
	})
	$('.coverselect').on('click','.imageholder a',function(){
		parent.applyBoxImage($(this).attr('href'));
		$('#cover-select').removeClass('md-custom-show');
		return false;
	})
	$('body').on('click', '#btnImgOk', function(){
		if($('input#chkCrop').is(':checked')){
		jQuery("#divToolImg").stop(true, true).fadeOut(0);
		jQuery("#divToolImgSettings").stop(true, true).fadeOut(0);
		jQuery('.overlay-bg').css('width', '100%');
		jQuery('.overlay-bg').css('height', '100%');
		//jQuery('body').css('overflow', 'hidden'); // This makes unwanted zoom-in in iOS Safari
		jQuery("#divToolImgLoader").css('top', jQuery('#divToolImg').css('top'));
		jQuery("#divToolImgLoader").css('left', jQuery('#divToolImg').css('left'));
		jQuery("#divToolImgLoader").css('display', 'block');
		}
	})
	$('body').on('click', '.is-boxes img', function(e){
		$(this).resizable({
			aspectRatio: true,
		});
		$(this).attr('draggable', false);
		e.stopPropagation();
	})
	$(document).click(function(e) {
		$('img.ui-resizable').css('display','inline');
		$('img.ui-resizable').resizable( "destroy" );
		if(!$(e.target).hasClass('ui-draggable') && !$(e.target).parents().hasClass('ui-draggable')){
			$('.customTools').css('opacity', 0);
		}
	});



@if(sizeof($uploads)==15)

	$('#media-select .allmedia').scroll(function(){
		$('#media-select .allmedia').infiniteScroll({
		  path: '#media-select .pagination li a[rel="next"]',
		  append: '#media-select .allmedia .imageholder',
		  history: false,
		  prefill: true
		});
	})
	$('#cover-select .allmedia').scroll(function(){
		$('#cover-select .allmedia').infiniteScroll({
		  path: '#cover-select .pagination li a[rel="next"]',
		  append: '#cover-select .allmedia .imageholder',
		  history: false,
		  prefill: true
		});
	})

@endif

})
</script>
<script src="{{ asset('builder/builderscript.js') }}" type="text/javascript"></script>

@include('admin._partials.buildercustomfeatures')
	<!-- Jquery easing -->
<script type="text/javascript" src="{{ IncludeAsset('public/js/jquery.easing.1.3.min.js') }}"></script>
<!--sticky header-->
<script type="text/javascript" src="{{ IncludeAsset('public/js/jquery.sticky.js') }}"></script>

<script>
  $(document).ready(function(){
    $("#sticky-nav-sticky-wrapper").sticky({bottomSpacing:200});
  });
</script>
</body>
</html>